name: Release to JitPack

on:
  workflow_dispatch:
  push:    
    branches: [ master ]

jobs:
  call-release:
    uses: zTig3r/workflows/.github/workflows/release_jitpack.yml@master
    with:
      prebuild: true
